{% set name = "fusepyng" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d7d5449b1aea9677297fe3fa0e0a14b66f17ed32485f0746c9fa6104a5e282c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    # Ideally, we'd have a CDT dependency on libfuse here.

test:
  imports:
    - fusepyng

about:
  home: https://github.com/rianhunter/fusepyng
  license: ISC
  license_family: BSD
  # https://github.com/fusepy/fusepy/pull/126
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Simple ctypes bindings for FUSE - a fork of fusepy
  description: |
    fusepyng is a Python module that provides a simple interface to FUSE on
    various operating systems. It's just one file and is implemented using
    ctypes.

    fusepyng is a fork of fusepy. We keep our code in sync with new code from
    there.
  dev_url: https://github.com/rianhunter/fusepyng

extra:
  recipe-maintainers:
    - djsutherland
