travis:
  secure:
    BINSTAR_TOKEN: MsnxiRk+NCBWoEcyGKKP+TfJk19FFsx+Ozg32IGkVm34B9AqCSj2IMAwcmiH5MDZB05YBorMDgq+8zWHozk46qPrh9Lt/vDW8k6ia5FkDkMFfYAfB2bpa8aHGUORIzYxwtClOiLHiu3Eizw6X4NQnspvq3Nu57iKxWctsFRk6ZhL4+JhKZlre7Vg8FR1gxd0l7EgkwZIGjMUWyOVyFogR6Aixt6GYmye0Z96mszpcekQ9nJ0ncwGjFpUBUslw6bcFZ44iYqkAh6QMzAuk5Mi3VJ5YtiYZc8p1wnv0gEu0GxCLSdWM4O8nnNtDiZeWsooJZ/VHQLmD1Z2v1O/IYETV2MDF7QqqyLRNpfON5Qgk+D4S/w45z7VRE0LuGSN1qUkiCR46o5lK/WzkGqrixEbpCSqmGIzBrM3q+EmcJocspBy3s17F+ov3NbmWQ9ThxRzUrm2zL3FFLmjj9+35WzD9FsqA+CDYm49eEylP3svjz2cqa++Umm1MU55bmtL5gxhHr8oDqV9PLoLsjJUq2wFWkGo6jVI9XHpbrFED+lmoX30yo83qGgW1/W+pwLXC7XkBI6NQeutYb0oEM3P7990fzCsCdKZlyD9v6EW0tCQls2CpMEhHjEeiuBne2Vpqd90cIskDqUqzS5c0eSZj3Yu0ea+F1NdIueaLdBjQg2TFqI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
